name: Bug Report
description: Create a bug report to help improve the Files website
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Before you start...
      options:
        - label: Have you refreshed the page? You might be using an old version of the site.
          required: true
        - label: Have you checked for an existing feature request on this topic? If there is one, post a comment on it instead.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what your idea is. Include things like possible use cases, drawbacks, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative solutions
      description: Describe more ways this problem could be solved.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (screenshots, mockups) relevant to this feature request.

        Tip: You can attach images by highlighting this area and dragging files into it.
